### PR TITLE
Add a Notebook.  Define notebooks directory structure. 

### PR DESCRIPTION
**Pull request by otto-AMA**
The goal of this push is to establish a baseline directory structure for creating notebooks.  

The structure so far:  
- utils commonly re-used across multiple notebooks make it into a top level `utils` directory.   
- when writing a notebook, place it into a directory with associated meta-data(IE spectral unmixing endmembers input, output file for notebooks that export). So for example. A notebook called `foo.ipynb` may exist in a directory called `Foobar`.
- Each time a directory is added, make note of it in the README.md file with a short description of the notebook, (as well as a relative path link to it). The description should offer a `ctrl-f` -able way to navigate the readme.   
  
This structure is definitely malleable. Please make suggestions in `issues`, or join the community slack if you haven't already:  

http://opendatacube.slack.com

### CODE REVIEW

**Comment by otto-AMA** [comment]
```
.
└── datacube-notebooks
    ├── LICENSE
    ├── notebooks
    │   └── Load Tutorial
    │              ├── diagrams
    │              │   ├── gpm_01.png
    │              │   └── rainy2.png
    │              └── loading_from_data_cube.ipynb
    ├── README.md
    └── utils
        └── notebooks
            └── display_map.py
```  
print out of the directory structure. (using `tree`)

**Comment by felipk101** [comment]
Otto, I would suggest also having a notebook in the parent directory that serves as an index? For example can contain the name of each notebook, a summary of what it does, and a hyperlink to the actual notebook. We could also curate this 'index notebook' with headings and catagories.

**Comment by otto-AMA** [comment]
That sounds like a good idea.  

I had something similar in mind when I posted the main README.md with a reference to the single notebook in there called **Loading Data** .  
  
Here is a screenshot: 

image
  
I wanted to eventually keep a structure like this  
https://github.com/jupyter/jupyter/wiki/A-gallery-of-interesting-Jupyter-Notebooks  
In the link above a listing of notebooks are front and center, taxonomized, and indexed.     

Are you proposing a README that's an *Intro to notebooks* followed by a link to a manifest file(ipynb) that displays all notebooks?

**Comment by otto-AMA** [comment]
@felipk101 I've added the manifest/index notebook. Let me know if it's what you had in mind.

**Comment by omad** [comment]
This looks like a good start.

If you haven't seen it, https://github.com/geoscienceAustralia/dea-notebooks/ is a scientist maintained collection of notebooks created within Digital Earth Australia which we could also use a model.

I don't think we need the top level `notebooks/` directory to start with. It doesn't add anything and just makes people click an extra time.

Other than that. Great!

**Comment by alexgleith** [comment]
I tend to agree with @omad, and think that removing a level of hierarchy is a good idea.

**Comment by felipk101** [comment]
@otto-AMA Can we have an index of notebooks in the read me as suggested and also in a landing page/index notebook. The reasoning behind this is that when the repository is cloned a user can navigate through a well curated notebook page to great notebook examples.

**Comment by otto-AMA** [comment]
New PR:
Added Vogelmann Forest degradation notebook.

**Comment by alexgleith** [comment]
We should probably merge this in, hey? Then add other notebooks in separate PRs...

**Pull request merged**
